/* Extracted from app.js */

function openGlobalSearch(initialQuery){
  var modal=document.getElementById('globalSearchModal');
  if(modal){
    modal.classList.add('active');
    var input=document.getElementById('globalSearchInput');
    if(input){
      // 支持传入初始搜索词
      if(initialQuery && initialQuery.trim()){
        input.value=initialQuery.trim();
        doGlobalSearch(initialQuery.trim());
      }else{
        input.value='';
        renderSearchHistory();
      }
      input.focus();
    }
  }
}
function closeGlobalSearch(){var modal=document.getElementById('globalSearchModal');if(modal)modal.classList.remove('active')}
function renderSearchHistory(){var history=getLS('search_history',[]);var container=document.getElementById('globalSearchResults');var hint=document.getElementById('globalSearchHint');if(history.length===0){hint.textContent='输入关键词开始搜索';container.innerHTML='';return}hint.textContent='搜索历史';var html='';history.slice(0,8).forEach(function(q,i){html+='<div class="search-history-item" data-query="'+esc(q)+'" tabindex="0" role="button"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>'+esc(q)+'</div>'});html+='<div class="search-history-item" id="clearSearchHistory" style="color:var(--text-muted);font-size:12px">清除搜索历史</div>';container.innerHTML=html;if(!container._histListener){container._histListener=true;container.addEventListener('click',function(e){var item=e.target.closest('[data-query]');if(item){document.getElementById('globalSearchInput').value=item.dataset.query;doGlobalSearch()}if(e.target.closest('#clearSearchHistory')){setLS('search_history',[]);renderSearchHistory()}})}}
function doGlobalSearch(query){if(!query.trim()){renderSearchHistory();return}clearTimeout(window._searchDebounce);window._searchDebounce=setTimeout(function(){_doGlobalSearch(query)},200)}
function _doGlobalSearch(query){var q=query.toLowerCase();var results=[];CSUST_DATA.colleges.forEach(function(col){col.majors.forEach(function(m){if(typeof m==='object'){if(m.name.toLowerCase().indexOf(q)>=0||col.name.toLowerCase().indexOf(q)>=0){results.push({title:m.name,desc:col.name+' | '+m.code+' | '+m.degree,type:'专业',action:"navigate('academic')",icon:svgIcon('graduation-cap',16)})}if(m.intro&&m.intro.toLowerCase().indexOf(q)>=0){results.push({title:m.name,desc:m.intro.substring(0,50)+'...',type:'专业',action:"navigate('academic')",icon:svgIcon('graduation-cap',16)})}if(m.career&&m.career.some(function(c){return c.toLowerCase().indexOf(q)>=0})){results.push({title:m.name+' - 就业方向',desc:m.career.join('、'),type:'专业',action:"navigate('academic')",icon:svgIcon('briefcase',16)})}if(m.courses&&m.courses.some(function(c){return c.toLowerCase().indexOf(q)>=0})){results.push({title:m.name+' - 课程',desc:m.courses.join('、'),type:'专业',action:"navigate('academic')",icon:svgIcon('file-text',16)})}}})});CSUST_DATA.competitions.forEach(function(c){if(c.name.toLowerCase().indexOf(q)>=0||c.category.toLowerCase().indexOf(q)>=0||c.description.toLowerCase().indexOf(q)>=0){results.push({title:c.name,desc:c.level+' | '+c.category+' | '+c.competition_period,type:'竞赛',action:"navigate('competition')",icon:svgIcon('trophy',16)})}});
// 同时搜索Hub竞赛数据
if(typeof _cachedCompetitions!=='undefined'&&_cachedCompetitions){_cachedCompetitions.forEach(function(c){if(c.name.toLowerCase().indexOf(q)>=0||(c.category||'').toLowerCase().indexOf(q)>=0||(c.description||'').toLowerCase().indexOf(q)>=0){results.push({title:c.name,desc:(c.level||'')+' | '+(c.category||'')+' | '+(c.organizer||''),type:'竞赛',action:"navigate('competition')",icon:svgIcon('trophy',16)})}});}
CSUST_DATA.faq.forEach(function(f){if(f.q.toLowerCase().indexOf(q)>=0||f.a.toLowerCase().indexOf(q)>=0){results.push({title:f.q,desc:f.a.substring(0,60)+'...',type:'FAQ',action:"navigate('ai');setTimeout(function(){quickAsk('"+f.q.replace(/'/g,"\\'")+"')},300)",icon:svgIcon('help-circle',16)})}});CSUST_DATA.scholarships.forEach(function(s){if(s.name.toLowerCase().indexOf(q)>=0||s.condition.toLowerCase().indexOf(q)>=0){results.push({title:s.name,desc:s.amount+' | '+s.condition,type:'奖助学金',action:"navigate('academic','scholarship')",icon:svgIcon('trophy',16)})}});CSUST_DATA.clubs.forEach(function(c){if(c.name.toLowerCase().indexOf(q)>=0||c.desc.toLowerCase().indexOf(q)>=0||c.type.toLowerCase().indexOf(q)>=0){results.push({title:c.name,desc:c.type+' | '+c.desc,type:'社团',action:"navigate('news','clubs')",icon:svgIcon('music',16)})}});CSUST_DATA.usefulLinks.forEach(function(l){if(l.name.toLowerCase().indexOf(q)>=0||l.desc.toLowerCase().indexOf(q)>=0){results.push({title:l.name,desc:l.desc,type:'链接',action:"window.open('"+l.url+"','_blank')",icon:svgIcon('link',16)})}});CSUST_DATA.shuttleBus.forEach(function(s){if(s.route.toLowerCase().indexOf(q)>=0||s.bus.toLowerCase().indexOf(q)>=0){results.push({title:s.route,desc:s.bus+' | '+s.schedule+' | '+s.duration,type:'校车',action:"navigate('campus','shuttle')",icon:svgIcon('bus',16)})}});var container=document.getElementById('globalSearchResults');var hint=document.getElementById('globalSearchHint');hint.textContent='找到 '+results.length+' 个结果';if(results.length===0){container.innerHTML='<div style="padding:24px;text-align:center;color:var(--text-muted)">未找到相关结果</div>';return}var html='';var showCount=Math.min(results.length,10);results.slice(0,showCount).forEach(function(r){html+='<div class="search-result-item" onclick="closeGlobalSearch();'+r.action+'"><div class="search-result-icon">'+r.icon+'</div><div class="search-result-info"><div class="search-result-title">'+esc(r.title)+'</div><div class="search-result-desc">'+esc(r.desc)+'</div></div><div class="search-result-type">'+esc(r.type)+'</div></div>'});if(results.length>10){html+='<div id="searchMoreBtn" style="padding:12px;text-align:center;font-size:13px;color:var(--accent);cursor:pointer;border-top:1px solid var(--border-subtle)" onclick="showMoreSearchResults()">显示更多结果（还有'+(results.length-10)+'个）</div>'}container.innerHTML=html;window._searchResults=results;window._searchShown=10;var history=getLS('search_history',[]);var idx=history.indexOf(query.trim());if(idx>=0)history.splice(idx,1);history.unshift(query.trim());if(history.length>20)history=history.slice(0,20);setLS('search_history',history)}
function showMoreSearchResults(){if(!window._searchResults)return;var results=window._searchResults;var shown=window._searchShown||10;var container=document.getElementById('globalSearchResults');var moreBtn=document.getElementById('searchMoreBtn');if(moreBtn)moreBtn.remove();var nextBatch=results.slice(shown,shown+10);var html='';nextBatch.forEach(function(r){html+='<div class="search-result-item" onclick="closeGlobalSearch();'+r.action+'"><div class="search-result-icon">'+r.icon+'</div><div class="search-result-info"><div class="search-result-title">'+esc(r.title)+'</div><div class="search-result-desc">'+esc(r.desc)+'</div></div><div class="search-result-type">'+esc(r.type)+'</div></div>'});if(shown+10<results.length){html+='<div id="searchMoreBtn" style="padding:12px;text-align:center;font-size:13px;color:var(--accent);cursor:pointer;border-top:1px solid var(--border-subtle)" onclick="showMoreSearchResults()">显示更多结果（还有'+(results.length-shown-10)+'个）</div>'}var tempDiv=document.createElement('div');tempDiv.innerHTML=html;while(tempDiv.firstChild)container.appendChild(tempDiv.firstChild);window._searchShown=shown+10;container.scrollTop=container.scrollHeight}
